### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by Kixiron** [domenicquirl/cstree#27]
- [ ] ~An alternative to `GreenNodeBuilder::token()` that allows passing an interned string as the node's text~
- [ ] Allow all of the various things that interact with interners to be generic over the key type, currently they all use `Spur`
- [x] Allow creating `GreenNodeBuilder`s from owned `NodeCache`s (and then getting the caches back later on) [78e54d59db06b89be0c792015efb34746a5fba72]
- [x] Allow creating `NodeCache`s from owned interners (and then getting the interners back later on) [78e54d59db06b89be0c792015efb34746a5fba72]
- [x] Allow getting mutable and immutable references to the interner stored within a `NodeCache` [cc5ea59d4bd4a53165ef7de2e23200160530ad75, 1f06786eb88cc11fb5cbdc115946badbb0ad85ab]
- [x] Allow debugging and displaying both `SyntaxNode` and `ResolvedNode` to `fmt::Write` sources (this would also allow `ResolvedNode`'s `Debug` and `Display` implementations to write directly to the formatted instead of creating an intermediate string) [3ef1e7e82b0d43237217cff06a9bc343751cbde9]

**Comment by domenicquirl** [comment]
Tackled most of this in the recent commits. I'm still not particularly fond of `GreenNodeBuilder::token_from_key` - especially with the new abilities to access the builder's interner, I don't see much difference between doing the look-up outside or inside the builder. If you think you really need it, please do some more convincing :D

The generic keys turned out to be way more hairy than anticipated. When looking at this, I remembered why the key is currently fixed: since we intern token strings, tokens store the interner key as their `text`. This means that, to be generic of those, not only the builder/cache need to be generic, but the token data itself. 

Generics in the green tree are problematic because
 * there is type-erasure going on, and
 * they leak _everywhere_. If token data is generic, that infects green tokens, green nodes, green tree iterators, syntax tokens, syntax nodes, etc.

All that's to say: there is significant benefit in having a fixed key type. I am especially wary of generics in the outer layers UI-wise as well, since we already have `Language` plus node data plus (on methods) `Interner` or `Resolver` going on. I always remind myself of this fellow from `SyntaxText`:

```rs
fn zip_texts<'it1, 'it2, It1, It2, I1, I2, L1, L2, D1, D2>(
    xs: &mut It1,
    ys: &mut It2,
    resolver_x: &I1,
    resolver_y: &I2,
) -> Option<()>
where
    It1: Iterator<Item = (&'it1 SyntaxToken<L1, D1>, TextRange)>,
    It2: Iterator<Item = (&'it2 SyntaxToken<L2, D2>, TextRange)>,
    I1: Resolver + ?Sized,
    I2: Resolver + ?Sized,
    D1: 'static,
    D2: 'static,
    L1: Language + 'it1,
    L2: Language + 'it2,
```

So I don't think this is something I want to do. It could be an alternative option to globally set the key size through features, but that would of course still mean you can only have one size everywhere.

I can publish a release with the other items in the meantime.

**Comment by domenicquirl** [comment]
New version is up! Since the other two are probably not happening (at least for now), I'll go ahead and close this.
