### ISSUE TITLE
Missing Iterator implementations

### ISSUE THREAD

**Issue by Kixiron** [domenicquirl/cstree#30]
`cstree::Children` implements `DoubleEndedIterator`, `ExactSizeIterator`, `FusedIterator` and many of the default methods for `Iterator` such as `.size_hint()`, but `cstree::syntax::SyntaxElementChildren` and `cstree::syntax::SyntaxNodeChildren` lack support for these, meaning that stuff dealing with the wrapper types aren't as efficient as they should be

**Comment by domenicquirl** [comment]
Not everything survived, but I added a lot of the additional iterator impls in the new version. `DoubleEndedIterator` didn't make it, because green nodes are position-agnostic, but red nodes aren't. The tree is threadsafe, so it could be done if the iterator tracks indices from both sides and operates accordingly, but that's another set of work and I'd want to see benchmarks before I put that in to see that it doesn't hurt tree traversal.

The other two traits are in, as is `size_hint` and a few other things.
