### ISSUE TITLE
`new` for GreenToken

### ISSUE THREAD

**Issue by kiranshila** [domenicquirl/cstree#35]
I'm trying to write a parser right now using the nom parser combinator crate, which seems a bit more bottom up than top down, so I was planning on building `GreenNode`s manually. The docs claim this is possible, but there is no `new` method for GreenToken while there is in rowan. That being the case, I'm not quite  sure how to use `GreenNode::new()` if I can't make leaves.

**Comment by domenicquirl** [comment]
Hi, and thanks for giving `cstree` a go!

I took `GreenToken::new` out of the public interface because in `rowan` you can just call it with a `SyntaxKind` and its text, but here we intern all our token texts so the actual token data only contains the interned key of the token text. We still _could_ provide a public constructor, but you would either have to do the String interning yourself and supply an already-interned key, or supply an interner for the token to use.

Since interning is also a topic for nodes (via `NodeCache`), have you thought about interning (both text and nodes) for your setup? It seems like without a cache you would lose out on a lot of the benefits of having the green trees in the first place, namely being able to de-duplicate your nodes and tokens.

One thing to consider with both of the approaches for `GreenToken::new` is that if I do that, I have no way of knowing that the key/interner you provide is the same across nodes. This is already the case for nodes from different trees, but at least within the same tree (or more correctly: all trees that use the same cache) it is currently given by the implementation that the interning agrees. 

Maybe the better thing to do here would be to think about making the node and token creation methods on `NodeCache` public so new tree elements can be created while retaining the de-duplication benefits and interner behaviour. I _think_ that should be possible without too much breakage.

**Comment by domenicquirl** [comment]
I'll close this for now as I haven't heard back from you and I've changed the internal interface here in a recent commit to improve performance.
